version: '3.6'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: GameShop
      MYSQL_USER: aitor97
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql:z
      - ./sql:/docker-entrypoint-initdb.d:z

  php-app:
    image: cyborg-img
    environment:
      DB_HOST: localhost
      DB_USER: aitor97
      DB_PASS: 12345
      DB_NAME: GameShop
      ADMIN_DNI: 12345678A
      ADMIN_NAME: admin
      ADMIN_SURNAME: admin
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PHONE: 111111111
      ADMIN_AGE: 99
      ADMIN_PASS: AdminDaw1234
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./ob.ini:/usr/local/etc/php/conf.d/ob.ini
    depends_on:
      - mariadb
