version: '3.6'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: GameShop
      MYSQL_USER: aitor97
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql:z
      - ./sql:/docker-entrypoint-initdb.d:z

  php-app:
    image: cyborg-img
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
